include $src_root

cxx.poptions =+ "-I$src_root/test/thirdparty/catch"
cxx.poptions =+ "-I$src_root/test/thirdparty/fifo_map"  

# Catch2 main().
# 
obj{catch_main}: cxx{unit} 
obj{catch_main}: cxx.poptions += "-DCATCH_CONFIG_FAST_COMPILE"

if ($cxx.class == 'msvc') 
{
  obj{catch_main}: cxx.poptions += "-D_SCL_SECURE_NO_WARNINGS"
  obj{catch_main}: cxx.coptions += "/EHsc" "/W4" "/wd4389" "/wd4309" \ 
                                    "/wd4566" "/wd4996"
}

# Unit tests.
#
exe{*}: test = true
exe{*}: install = false  

for t: cxx{unit-*}
{
  n = $name($t)        
  ./: exe{$n}
  exe{$n}: $t obj{catch_main} $src_root/lib{nlohmann_json} 
}
