#include $src_root
#include $src_root/test/

# Unit tests.
#
exe{*}: test = true
exe{*}: install = false  

for t: cxx{unit-*}
{
  n = $name($t)        
  ./: exe{$n}
  exe{$n}: $src_root/test/liba{catch_main} \
           $src_root/lib{nlohmann_json}
  # exe{$n}: liba{catch_main} lib{nlohmann_json}
}
